version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - metadata-service
      - model-service
    networks:
      - data_network

  metadata-service:
    build: ./src/metadata
    container_name: metadata-service
    volumes:
      - ./utils:/app/utils
      - ./core:/app/core
    env_file:
      - ./.env
    networks:
      - data_network

  model-service:
    build: ./src/model
    container_name: model-service
    volumes:
    - ./utils:/app/utils
    - ./core/config:/app/core
    env_file:
      - ./.env
    networks:
      - data_network


networks:
  data_network:
    driver: bridge
    name: data_network